# fuzzel.ini - simple and readable theme

[main]
font=JetBrainsMono Nerd Font Mono:size=10
icon-theme=Papirus-Dark
icons-enabled=yes
prompt=
placeholder=Recherche…
lines=8
width=34
horizontal-pad=20
vertical-pad=14
inner-pad=15
line-height=20
icon-size=14
anchor=top
y-margin=12
layer=overlay
use-bold=no
match-mode=fzf

[colors]
background=181c22f0
text=eeeeeeff
prompt=9aa8bcff
placeholder=888888ff
input=eeeeeeff
match=7ea2ffff
selection=23272eff
selection-text=eeeeeeff
selection-match=ffe082ff
border=181c2200

[border]
width=0
radius=0
selection-radius=0