# Hyprpaper configuration
# Replace the path below with your wallpaper file.

preload = /home/jonathan/Images/wallpapers/main.jpg
wallpaper = eDP-1,/home/jonathan/Images/wallpapers/main.jpg

# Optional: keep this enabled to improve image quality on scaling
splash = false
