# BACKGROUND
background {
    monitor =
    path = /home/jonathan/Images/wallpapers/main.jpg
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, 0.70)
    font_size = 25
    font_family = Monospace
    position = 0, 350
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(216, 222, 233, 0.70)
    font_size = 120
    font_family = Monospace
    position = 0, 250
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 300, 60
    color = rgba(255, 255, 255, .1)
    rounding = -1
    border_size = 0
    rotate = 0
    position = 0, -100
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = $USER
    color = rgba(216, 222, 233, 0.80)
    font_size = 18
    font_family = Monospace
    position = 0, -100
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = Monospace
    placeholder_text = Mot de passe
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

# Empreinte
label {
    monitor =
    text = Empreinte disponible
    color = rgba(255, 255, 255, 0.4)
    font_size = 12
    font_family = Monospace
    position = 0, -260
    halign = center
    valign = center
}

# FINGERPRINT
auth {
    fingerprint {
        enabled = true
        ready_message =
        present_message =
    }
}
